[build]
publish = "dist/"

[[redirects]]
from = "/api/*"
to = "https://careapi.coronasafe.in/api/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
[build]
  publish = "build" # Ensure this matches your build folder
  command = "npm run build" # Replace with your actual build command

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "DENY"
    Content-Security-Policy = "frame-ancestors 'none';"

