// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

function decode(json) {
  return {
          id: Json_decode.field("id", Json_decode.string, json),
          roomTypeText: Json_decode.field("room_type_text", Json_decode.string, json),
          modifiedDate: Json_decode.field("modified_date", Json_decode.string, json),
          totalCapacity: Json_decode.field("total_capacity", Json_decode.$$int, json),
          currentCapacity: Json_decode.field("current_capacity", Json_decode.$$int, json)
        };
}

exports.decode = decode;
/* No side effect */
