// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Capacity = require("./Capacity.bs.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

function decode(json) {
  return {
          name: Json_decode.field("id", Json_decode.string, json),
          districtId: Json_decode.field("room_type_text", Json_decode.string, json),
          district: Json_decode.field("modified_date", Json_decode.string, json),
          oxygenCapacity: Json_decode.field("total_capacity", Json_decode.$$int, json),
          capacity: Json_decode.field("capacity", (function (param) {
                  return Json_decode.array(Capacity.decode, param);
                }), json)
        };
}

exports.decode = decode;
/* No side effect */
